
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: dio
    password: Dio@22
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update